---

name: "Feature request"
description: "Suggest an idea for this project"
title: "FEATURE: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: description
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please describe your idea"
      placeholder: |
        A clear and concise description of what the problem is.

        *I'm always frustrated when [...]*

    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "What solutions have you considered?"
      description: "Describe the solution you'd like"
      placeholder: |
        A clear and concise description of what you want to happen.

    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "What alternatives have you considered?"
      description: "Describe any alternative solutions you've considered"
      placeholder: |
        A clear and concise description of any alternative or existing solutions or features you've considered.

        If relevant, please explain why your solution is preferable.

    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: |
        Please Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct"
      description: |
        By submitting this issue, you agree to follow the [Code of Conduct](https://github.com/jirastopwatch/.github/blob/main/CODE_OF_CONDUCT.md)

      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
